spring:
  datasource:
    username: root
    password: "Mcpd105!"
    url: jdbc:mysql://localhost:3306/empDB2
  driver-class-name: com.mysql.cj.jdbc.Driver
  
#data jap spec

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
    